

server:
  port: 8012

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/knocksea
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB #1개의 파일의 최대사이즈
      max-request-size: 20MB # 전체 요청의 최대사이즈

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: KfvIJyXEhbOrrzxCCI+qmsIuslRItPtj2Ee+fhUUU0Ik9CBCpM/KV+N6Fc+H7mYJL7GBeOqpzEMaoe5C8+M5Mw==

# 업로드파일 저장 경로
upload:
  path: D:/knocksea_upload

kakao:
  admin:
    key: b0e82271a5b48b26d2e65429c52085c1
